from enum import Enum

class DocType(str, Enum):
    ENDIVIDAMENTO = "ENDIVIDAMENTO"
    RECEBIVEIS = "RECEBIVEIS"
    TIPOLOGIA = "TIPOLOGIA"
    LANDBANK = "LANDBANK"
    BALANCO = "BALANCO"
    DRE = "DRE"
    FATURAMENTO = "FATURAMENTO"
    VIABILIDADE = "VIABILIDADE"     # <--- Novo
    TABELA_VENDAS = "TABELA_VENDAS"
    CONTRATO_SOCIAL = "CONTRATO_SOCIAL" # <--- Novo
    CRONOGRAMA = "CRONOGRAMA"       # <--- Novo
    OUTRO = "OUTRO"