from enum import Enum

class DocType(str, Enum):
    ENDIVIDAMENTO = "ENDIVIDAMENTO"
    RECEBIVEIS = "RECEBIVEIS"
    TIPOLOGIA = "TIPOLOGIA"
    LANDBANK = "LANDBANK"
    BALANCO = "BALANCO"
    DRE = "DRE"
    FATURAMENTO = "FATURAMENTO"
    TABELA_VENDAS = "TABELA_VENDAS"
    CONTRATO_SOCIAL = "CONTRATO_SOCIAL"
    OUTRO = "OUTRO"
